# - name: Check for network
#   avi_api_session:
#     avi_credentials: "{{ avi_credentials }}"
#     http_method: get
#     path: vimgrnwruntime
#     params: 
#       name: "{{ seg_management_network_portgroup }}"
#   until: network_lookup_result.obj.results.0 is defined
#   retries: 30
#   delay: 10
#   register: network_lookup_result

- name: defining avi config
  set_fact:
    avi_config:

    #- name: ContentSwitch1 pool
      pool:
      - name: "ContentSwitch1"
        tenant: "{{tenant_name}}"
        cloud_ref: "/api/cloud/?name={{cloud_name}}"
        servers:
          - port: 80
            ip:
              addr: "{{ static_web2 }}"
              type: V4
          - port: 80
            ip:
              addr: "{{ static_web1 }}"
              type: V4          
        fail_action:
          type: "FAIL_ACTION_CLOSE_CONN"

    #- name: ContentSwitch2 dummy pool
      - name: "ContentSwitch2"
        tenant: "{{tenant_name}}"
        cloud_ref: "/api/cloud/?name={{cloud_name}}"
        servers:
          - hostname: "fake_server2"
            port: 80
            ip:
              addr: 10.79.186.100
              type: V4
        fail_action:
          type: "FAIL_ACTION_CLOSE_CONN"

    #- name: configure demoavi pool
      - name: DemoInACan-pool
        analytics_policy:
          enable_realtime_metrics: true
        cloud_ref: "/api/cloud/?name={{cloud_name}}"
        fail_action:
          type: FAIL_ACTION_CLOSE_CONN
        graceful_disable_timeout: 180
        health_monitor_refs:
        - /api/healthmonitor/?name=System-HTTP
        lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
        server_reselect:
          enabled: false
        servers:
          - port: 80
            ip:
              addr: "{{ avi_web1 }}"
              type: V4
          - port: 80
            ip:
              addr: "{{ avi_web2 }}"
              type: V4
          - port: 80
            ip:
              addr: "{{ avi_web3 }}"
              type: V4     
          - hostname: "fake_server"
            port: 80
            ip:
              addr: 10.79.186.100
              type: V4         
        tenant: "{{tenant_name}}"




    #- name: configure demoavi vsvip
      vsvip:
      - name: "vsvip-demoinacan"
        cloud_ref: "/api/cloud/?name={{cloud_name}}"
        dns_info:
        - fqdn: "can-demo.c{{controller_number}}.avidemo.vmware.com"
          ttl: 5

        tenant: "{{tenant_name}}"
        vip:
          - vip_id: "0"
            auto_allocate_ip: true
            # network_ref: "/api/network/{{network_lookup_result.obj.results.0.uuid}}"
    

    #- name: configure http policy set
      httppolicyset:
      - name: demoinacan-HTTP-Policy-Set
        is_internal_policy: false
        tenant: "{{tenant_name}}"
        http_request_policy:
          rules:
          - enable: true
            index: 1
            match:
              path:
                match_case: INSENSITIVE
                match_criteria: CONTAINS
                match_str:
                - contactus
            name: ContentSwitch2
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              pool_ref: /api/pool/?name=ContentSwitch2
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
          - enable: true
            index: 2
            match:
              path:
                match_case: INSENSITIVE
                match_criteria: CONTAINS
                match_str:
                - /downloads
            name: ContentSwitch1
            rewrite_url_action:
              path:
                tokens:
                - str_value: ''
                  type: URI_TOKEN_TYPE_STRING
                type: URI_PARAM_TYPE_TOKENIZED
              query:
                keep_query: false
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              pool_ref: /api/pool/?name=ContentSwitch1
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200


    #- name: configure demoavi
      virtualservice:
      - name: DemoInACan-VS
        analytics_policy:
          all_headers: true
          client_insights: ACTIVE
          full_client_logs:
            duration: 0
            enabled: true
            throttle: 0
          metrics_realtime_update:
            duration: 0
            enabled: true
          significant_log_throttle: 0
          udf_log_throttle: 0
        application_profile_ref: /api/applicationprofile/?name=System-Secure-HTTP
        cloud_ref: "/api/cloud/?name={{cloud_name}}"
        cloud_type: "CLOUD_VCENTER"
        http_policies:
        - http_policy_set_ref: /api/httppolicyset/?name=demoinacan-HTTP-Policy-Set
          index: 11
        network_profile_ref: /api/networkprofile/?name=System-TCP-Proxy
        pool_ref: "/api/pool/?name=DemoInACan-pool"
        services:
        - enable_ssl: false
          port: 80
          port_range_end: 80
        - enable_ssl: true
          port: 443
          port_range_end: 443
        ssl_key_and_certificate_refs:
          - "/api/sslkeyandcertificate/?name=entrust_ec_cert_app"
          - "/api/sslkeyandcertificate?name=entrust_rsa_cert_app"
        ssl_profile_ref: /api/sslprofile/?name=System-Standard
        tenant: "{{tenant_name}}"
        traffic_enabled: true
        vsvip_ref: "/api/vsvip/?name=vsvip-demoinacan"



- name: Avi Application | Setup Content Switch VS
  import_role:
    name: avinetworks.aviconfig
  vars:
    avi_config: "{{avi_config}}"